version: '3'

services:
    http2_php7:
          image: php:7.1-fpm
          container_name: http2_php7
          expose:
              - 9000
          volumes:
            - ./web:/var/www/html/web
          tty: true
    http2_apache:
        build: ./docker/http2_apache
        container_name: http2_apache
        ports:
            - 90:80
        links:
            - http2_php7
        volumes:
            - ./web:/var/www/html/web
        tty: true
    http_apache:
        build: ./docker/http_apache
        container_name: http_apache
        ports:
            - 91:80
        links:
            - http2_php7
        volumes:
            - ./web:/var/www/html/web
        tty: true
    http2_nginx:
        build: ./docker/nginx
        container_name: http2_nginx
        ports:
            - 92:80
            - 93:443
        links:
            - http2_php7
        volumes:
            - ./web:/var/www/html/web
        tty: true

#volumes:
#    web:
##      driver: local
#      driver_opts:
##          source: /web
#            type: nfs
#            device: :/home/xavier/others/http2/web2
#            o: bind