FROM nginx

ADD vhost.conf /etc/nginx/sites-available/


#RUN ln -s /etc/nginx/sites-available/vhost.conf /etc/nginx/sites-enabled/vhost2

#RUN rm /etc/nginx/sites-enabled/default

CMD ["nginx"]

EXPOSE 80
EXPOSE 443